
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      script:
        - make all install
    - language: c
      script:
        - make COVERAGE="-g -coverage" all install
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
