
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      script:
        - ./configure --with-target=debug && sudo make all install
    - language: c
      script:
        - ./configure --with-target=release && sudo make all install
    - language: c
      script:
        - ./configure --with-target=coverage && sudo make all install test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
