
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      cache:
        directories:
          - .
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make all install
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make COVERAGE="-g -coverage" all install
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
