
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      script:
        - ./configure && sudo make all setup
    - language: c
      script:
        - ./configure && sudo make COVERAGE="-g -coverage -DBFI_NOCHECKS -O0" all setup test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
